# coding=utf-8

trello_dict = {
    "#时间管理 '日·": "https://trello.com/c/RIRS417M",
    "#生活/日常 '天气<应用:墨迹天气>'": "https://trello.com/c/JYtBByM5",
    "#公司(乐视)/管理 '考勤'": "https://trello.com/c/KyBHGd7r",
    "#日常/办公 '邮件'": "https://trello.com/c/KanqtvUt",
    "#人文/语言(英语) '单词<应用:知米背单词>'": "https://trello.com/c/YDjCQ0vS",
    "#人文/语言(英语) '单词<应用:扇贝单词>'": "https://trello.com/c/uI1zWyEU",
    "#生活/行/车(比亚迪·秦) '充电·": "https://trello.com/c/JotLTWjl",
    "#生命/健康 '锻炼·散步'": "https://trello.com/c/T3DBFGe8",
    "#ADE(Android)/DTC/BS 'Gradle·plugin'": "https://trello.com/c/MCzn1NMi",
    "#ADE(Android)/DTC/BS 'Gradle·Sync": "https://trello.com/c/tlNQ7ZwL",
    "#时间管理 '休假·": "https://trello.com/c/IwnTjw5z",
    "#社交/亲/子(刘枢鸿) '作业": "https://trello.com/c/OP2j3pkV",
    "#生活/食 '做饭": "https://trello.com/c/n33fHx8L",
    "#时间管理 '工具": "https://trello.com/c/5uLm7R7g",
    "#产品(EUI)/App '全视频TV桌面": "https://trello.com/c/J4f7LxXs",
    "#项目管理 '方法(康桦)": "https://trello.com/c/WZbJWhQh",
    "#软件/应用 '笔记(有道云笔记)": "https://trello.com/c/ZvvtYvkc",
    # 月度
    "#金融/服务/银行(中行) '信用卡": "https://trello.com/c/jfOdGClU",
    "#金融/服务/银行(招行) '信用卡": "https://trello.com/c/fHAuY8ht",
    "#社交/友 '施王兴": "https://trello.com/c/7Zr1ghMA",
    "#生活/行/车(福特·蒙迪欧) '进京证": "https://trello.com/c/p1JrhG0Y",
    "#软件/应用 '考勤小助·": "https://trello.com/c/bYbl8TwV",
    "#财经/理财 '腾讯理财通": "https://trello.com/c/F3UlTT5v",
    "ADE(Android)/DevEnv 'AS": "https://trello.com/c/E3QwUyp4",
    "项目(TV) '会议·周会": "https://trello.com/c/zCPxwtEo",
    "生活/乐 '电影": "https://trello.com/c/Sl1sRtiT",
    "#金融/服务/银行(建设) '信用卡": "https://trello.com/c/nbbmxlyT",
    "#生活/用/IT '无线路由器·实例(艾泰A655W)·": "https://trello.com/c/XA4yWMT2",
    "生活/用/IT '无线路由器": "https://trello.com/c/bd3v2XXx",
    "#财经/理财 '医保存折·入账": "https://trello.com/c/srSi79Ys",
    "#项目(TV)/平台 'T972·": "https://trello.com/c/wwldtCRS",
    "#Programmer/Lib/Math 'GUID": "https://trello.com/c/pdUnMwUD",
    "#Programmer/Lib 'utils(utils4j)": "https://trello.com/c/JxVtAvys",
    "#生活/行/车(比亚迪·秦) '事故": "https://trello.com/c/QI5DPn23",
    "#生活/用 '宽带<ISP:中国联通>·": "https://trello.com/c/HQtIGKRz",
    "#社交/亲/子(刘枢鸿) '活动·": "https://trello.com/c/xImA80FW",
    "#生命/健康 '就诊<医生:王毅>'@刘显珂": "https://trello.com/c/zWt3s7sR",
    "#软件/应用 'e充电": "https://trello.com/c/kn337Pjp",
    "#生活/用/IT '智能摄像机·": "https://trello.com/c/9G9WBfxh",
    "#生活/用/IT '智能摄像机(360云台版)·": "https://trello.com/c/rFPkRIYC",
    "#ADE(Android)/Lib 'View(EditText)·": "https://trello.com/c/gz7PDAQk",
    "#生命/健康(刘枢鸿) '就诊": "https://trello.com/c/5QaUXoyF",
    "#财经/金融 '贷款(公积金)": "https://trello.com/c/4jyyYk8U",
}